//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.Addresses = new HashSet<Address>();
            this.Addresses1 = new HashSet<Address>();
            this.Addresses2 = new HashSet<Address>();
            this.Addresses3 = new HashSet<Address>();
            this.AddressTypes = new HashSet<AddressType>();
            this.AddressTypes1 = new HashSet<AddressType>();
            this.AddressTypes2 = new HashSet<AddressType>();
            this.AddressTypes3 = new HashSet<AddressType>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.EmailAddresses = new HashSet<EmailAddress>();
            this.EmailAddresses1 = new HashSet<EmailAddress>();
            this.EmailAddresses2 = new HashSet<EmailAddress>();
            this.EmailAddresses3 = new HashSet<EmailAddress>();
            this.EmailTypes = new HashSet<EmailType>();
            this.EmailTypes1 = new HashSet<EmailType>();
            this.EmailTypes2 = new HashSet<EmailType>();
            this.EmailTypes3 = new HashSet<EmailType>();
            this.Events = new HashSet<Event>();
            this.Events1 = new HashSet<Event>();
            this.Events2 = new HashSet<Event>();
            this.Events3 = new HashSet<Event>();
            this.EventTypes = new HashSet<EventType>();
            this.EventTypes1 = new HashSet<EventType>();
            this.EventTypes2 = new HashSet<EventType>();
            this.EventTypes3 = new HashSet<EventType>();
            this.Groups = new HashSet<Group>();
            this.Groups1 = new HashSet<Group>();
            this.Groups2 = new HashSet<Group>();
            this.Groups3 = new HashSet<Group>();
            this.IMAccounts = new HashSet<IMAccount>();
            this.IMAccounts1 = new HashSet<IMAccount>();
            this.IMAccounts2 = new HashSet<IMAccount>();
            this.IMAccounts3 = new HashSet<IMAccount>();
            this.IMTypes = new HashSet<IMType>();
            this.IMTypes1 = new HashSet<IMType>();
            this.IMTypes2 = new HashSet<IMType>();
            this.IMTypes3 = new HashSet<IMType>();
            this.PersonCompanies = new HashSet<PersonCompany>();
            this.PersonCompanies1 = new HashSet<PersonCompany>();
            this.PersonCompanies2 = new HashSet<PersonCompany>();
            this.PersonCompanies3 = new HashSet<PersonCompany>();
            this.Persons = new HashSet<Person>();
            this.Persons1 = new HashSet<Person>();
            this.Persons2 = new HashSet<Person>();
            this.Persons3 = new HashSet<Person>();
            this.PersonsInGroups = new HashSet<PersonsInGroup>();
            this.PersonsInGroups1 = new HashSet<PersonsInGroup>();
            this.PersonsInGroups2 = new HashSet<PersonsInGroup>();
            this.PersonsInGroups3 = new HashSet<PersonsInGroup>();
            this.PhoneNumbers = new HashSet<PhoneNumber>();
            this.PhoneNumberTypes = new HashSet<PhoneNumberType>();
            this.PhoneNumbers1 = new HashSet<PhoneNumber>();
            this.PhoneNumberTypes1 = new HashSet<PhoneNumberType>();
            this.PhoneNumbers2 = new HashSet<PhoneNumber>();
            this.PhoneNumberTypes2 = new HashSet<PhoneNumberType>();
            this.PhoneNumbers3 = new HashSet<PhoneNumber>();
            this.PhoneNumberTypes3 = new HashSet<PhoneNumberType>();
            this.Relationships = new HashSet<Relationship>();
            this.RelationshipTypes = new HashSet<RelationshipType>();
            this.Relationships1 = new HashSet<Relationship>();
            this.RelationshipTypes1 = new HashSet<RelationshipType>();
            this.Relationships2 = new HashSet<Relationship>();
            this.RelationshipTypes2 = new HashSet<RelationshipType>();
            this.Relationships3 = new HashSet<Relationship>();
            this.RelationshipTypes3 = new HashSet<RelationshipType>();
            this.Websites = new HashSet<Website>();
            this.Websites1 = new HashSet<Website>();
            this.Websites2 = new HashSet<Website>();
            this.Websites3 = new HashSet<Website>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string FullName { get; set; }
        public string ImageData { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Address> Addresses1 { get; set; }
        public virtual ICollection<Address> Addresses2 { get; set; }
        public virtual ICollection<Address> Addresses3 { get; set; }
        public virtual ICollection<AddressType> AddressTypes { get; set; }
        public virtual ICollection<AddressType> AddressTypes1 { get; set; }
        public virtual ICollection<AddressType> AddressTypes2 { get; set; }
        public virtual ICollection<AddressType> AddressTypes3 { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<EmailAddress> EmailAddresses { get; set; }
        public virtual ICollection<EmailAddress> EmailAddresses1 { get; set; }
        public virtual ICollection<EmailAddress> EmailAddresses2 { get; set; }
        public virtual ICollection<EmailAddress> EmailAddresses3 { get; set; }
        public virtual ICollection<EmailType> EmailTypes { get; set; }
        public virtual ICollection<EmailType> EmailTypes1 { get; set; }
        public virtual ICollection<EmailType> EmailTypes2 { get; set; }
        public virtual ICollection<EmailType> EmailTypes3 { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Event> Events1 { get; set; }
        public virtual ICollection<Event> Events2 { get; set; }
        public virtual ICollection<Event> Events3 { get; set; }
        public virtual ICollection<EventType> EventTypes { get; set; }
        public virtual ICollection<EventType> EventTypes1 { get; set; }
        public virtual ICollection<EventType> EventTypes2 { get; set; }
        public virtual ICollection<EventType> EventTypes3 { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Group> Groups1 { get; set; }
        public virtual ICollection<Group> Groups2 { get; set; }
        public virtual ICollection<Group> Groups3 { get; set; }
        public virtual ICollection<IMAccount> IMAccounts { get; set; }
        public virtual ICollection<IMAccount> IMAccounts1 { get; set; }
        public virtual ICollection<IMAccount> IMAccounts2 { get; set; }
        public virtual ICollection<IMAccount> IMAccounts3 { get; set; }
        public virtual ICollection<IMType> IMTypes { get; set; }
        public virtual ICollection<IMType> IMTypes1 { get; set; }
        public virtual ICollection<IMType> IMTypes2 { get; set; }
        public virtual ICollection<IMType> IMTypes3 { get; set; }
        public virtual ICollection<PersonCompany> PersonCompanies { get; set; }
        public virtual ICollection<PersonCompany> PersonCompanies1 { get; set; }
        public virtual ICollection<PersonCompany> PersonCompanies2 { get; set; }
        public virtual ICollection<PersonCompany> PersonCompanies3 { get; set; }
        public virtual ICollection<Person> Persons { get; set; }
        public virtual ICollection<Person> Persons1 { get; set; }
        public virtual ICollection<Person> Persons2 { get; set; }
        public virtual ICollection<Person> Persons3 { get; set; }
        public virtual ICollection<PersonsInGroup> PersonsInGroups { get; set; }
        public virtual ICollection<PersonsInGroup> PersonsInGroups1 { get; set; }
        public virtual ICollection<PersonsInGroup> PersonsInGroups2 { get; set; }
        public virtual ICollection<PersonsInGroup> PersonsInGroups3 { get; set; }
        public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
        public virtual ICollection<PhoneNumberType> PhoneNumberTypes { get; set; }
        public virtual ICollection<PhoneNumber> PhoneNumbers1 { get; set; }
        public virtual ICollection<PhoneNumberType> PhoneNumberTypes1 { get; set; }
        public virtual ICollection<PhoneNumber> PhoneNumbers2 { get; set; }
        public virtual ICollection<PhoneNumberType> PhoneNumberTypes2 { get; set; }
        public virtual ICollection<PhoneNumber> PhoneNumbers3 { get; set; }
        public virtual ICollection<PhoneNumberType> PhoneNumberTypes3 { get; set; }
        public virtual ICollection<Relationship> Relationships { get; set; }
        public virtual ICollection<RelationshipType> RelationshipTypes { get; set; }
        public virtual ICollection<Relationship> Relationships1 { get; set; }
        public virtual ICollection<RelationshipType> RelationshipTypes1 { get; set; }
        public virtual ICollection<Relationship> Relationships2 { get; set; }
        public virtual ICollection<RelationshipType> RelationshipTypes2 { get; set; }
        public virtual ICollection<Relationship> Relationships3 { get; set; }
        public virtual ICollection<RelationshipType> RelationshipTypes3 { get; set; }
        public virtual ICollection<Website> Websites { get; set; }
        public virtual ICollection<Website> Websites1 { get; set; }
        public virtual ICollection<Website> Websites2 { get; set; }
        public virtual ICollection<Website> Websites3 { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
