//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<bool> IsEveryYearEvent { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<bool> IsEmailReminder { get; set; }
        public Nullable<int> SelectedEmailAddressId { get; set; }
        public string EmailMessage { get; set; }
        public Nullable<int> RemindBeforeDays { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual EmailAddress EmailAddress { get; set; }
        public virtual EmailAddress EmailAddress1 { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual EventType EventType1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
